### ISSUE TITLE
Visual Glitch on closing the Activity

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [sidlatau/flutter_document_picker#10]
![documentpickervisualglitch](https://user-images.githubusercontent.com/23037821/46388346-5771f600-c680-11e8-85af-de591ab575c0.gif)
This only happens the first time it's opened, but is there a way this can be fixed?
Gif is slowed down

**Comment by sidlatau** [comment]
Hm, I haven't noticed any glitch in my app. Does this glitch still appear? Does it appear in the real device too?
