### ISSUE TITLE
No named parameter with the name 'allowedMimeType'

### ISSUE THREAD

**Issue by abdul-vahid** [sidlatau/flutter_document_picker#14]
Hi,
Here in the following snippet, it shows me that allowedMimeType is not a parameter, can you please let me know how we can resolve it?

FlutterDocumentPickerParams params = FlutterDocumentPickerParams(
        **allowedMimeType:** _checkByMimeType ? _mimeTypeController.text : null,
        allowedFileExtensions: _checkByCustomExtension
            ? _extensionController.text
            .split(' ')
            .where((x) => x.isNotEmpty)
            .toList()
            : null,
        allowedUtiTypes: _iosPublicDataUTI
            ? null
            : _utiController.text
            .split(' ')
            .where((x) => x.isNotEmpty)
            .toList(),

      );

**Comment by sidlatau** [comment]
What is an exact error message? Are you using the latest version of the plugin? Currently latest version is [v1.1.3](https://pub.dartlang.org/packages/flutter_document_picker#-installing-tab-)

**Comment by abdul-vahid** [comment]
Hi sidlatau,

The issue has been resolved when I run flutter doctorate command, but I am finding new issue that when I am running your example it keep showing me Resolving Dependency and app is not working...

https://pub.dartlang.org/packages/flutter_document_picker#-example-tab-

![image](https://user-images.githubusercontent.com/5676448/47959271-92f83b00-e005-11e8-9aa2-0de59bc250fd.png)

**Comment by abdul-vahid** [comment]
Now I am getting this error:

Launching lib\main.dart on XT1663 in debug mode...
Initializing gradle...
Resolving dependencies...
timeout waiting for the application to start
* Error running Gradle:
Exit code 1 from: F:\flatter\filepicker\android\gradlew.bat app:properties:
Starting a Gradle Daemon, 4 busy Daemons could not be reused, use --status for details
Download https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.2.1/builder-3.2.1.jar
Download https://dl.google.com/dl/android/maven2/com/android/tools/analytics-library/protos/26.2.1/protos-26.2.1.jar
Download https://dl.google.com/dl/android/maven2/com/android/tools/build/gradle/3.2.1/gradle-3.2.1.jar
Download https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-stdlib/1.2.71/kotlin-stdlib-1.2.71.jar
Download https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-compiler-embeddable/1.2.71/kotlin-compiler-embeddable-1.2.71.jar
Download https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-daemon-client/1.2.71/kotlin-daemon-client-1.2.71.jar
Download https://jcenter.bintray.com/org/jetbrains/kotlin/kotlin-build-common/1.2.71/kotlin-build-common-1.2.71.jar


FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_document_picker'.
> Could not resolve all files for configuration ':flutter_document_picker:classpath'.
   > Could not download builder.jar (com.android.tools.build:builder:3.2.1)
      > Could not get resource 'https://dl.google.com/dl/android/maven2/com/android/tools/build/builder/3.2.1/builder-3.2.1.jar'.
         > Premature end of Content-Length delimited message body (expected: 28300680; received: 4456416

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 6m 33s

Finished with error: Please review your Gradle project setup in the android/ folder.

**Comment by abdul-vahid** [comment]
All Issues have been resolved now I can see you and able to select file. Thanks
