### ISSUE TITLE
Load local files instead of iCloud Drive on iOS

### ISSUE THREAD

**Issue by ricsmania** [sidlatau/flutter_document_picker#16]
I got this working with iOS, but it only shows iCloud Drive files. Is there a way to open local files, for example photos taken with the camera?

**Comment by daryll-fourie** [comment]
Hi, is there any feedback regarding this?

**Comment by sidlatau** [comment]
I am using `UIDocumentPickerViewController` in plugin. I haven't find a way to show images using this controller. You can check [image_picker](https://pub.dartlang.org/packages/image_picker) plugin for picking images.

**Comment by santa010** [comment]
But is there a way to show local files (that are not images)?
