### ISSUE TITLE
Unable to run on ios

### ISSUE THREAD

**Issue by prabha32** [sidlatau/flutter_document_picker#18]
I was unable to compile the plugin on iOS. 
Error: The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.

**Comment by sidlatau** [comment]
It looks like issue #8 - check this comment:
> It looks like an [issue](https://github.com/flutter/flutter/issues/16049) registered in flutter repo, when trying to add swift plugin to objective-c project. Check this comment for possible fix:
> [flutter/flutter#16049 (comment)](https://github.com/flutter/flutter/issues/16049#issuecomment-382629492)

**Comment by jhj** [comment]
I was able to get past this error by inserting `s.swift_version='4.0'` in `flutter_document_picker/ios/flutter_document_picker.podspec`
