### ISSUE TITLE
Allow multiple mime types

### ISSUE THREAD

**Issue by boskokg** [sidlatau/flutter_document_picker#19]
Hello,
Thanks for this plugin.
Can you add support for multiple mime types instead of only single one?
For example, I would like to filter only pdf and image files (image/*|application/pdf)

**Comment by sidlatau** [comment]
v3.0.0 was released to Pub with the ability to filter by multiple MIME types. Example:
```dart
final params = FlutterDocumentPickerParams(      
  allowedMimeTypes: ['application/pdf', 'image/png'],
);

final path = await FlutterDocumentPicker.openDocument(params: params);
```

**Comment by frank-jong** [comment]
How can I only see and select .gpx files? 
Appreciate your answer. :-)
