### ISSUE TITLE
Thread 1: EXC_BAD_ACCESS (code=2, address=0x16f19ffe0)

### ISSUE THREAD

**Issue by diazsasak** [sidlatau/flutter_document_picker#20]
![screen shot 2019-02-07 at 09 18 29](https://user-images.githubusercontent.com/7880137/52384683-7d3d5a80-2ab9-11e9-9341-86a6e3be3723.png)

its some kind of infinite looping. my app is stuck white screen. thanks

**Comment by sidlatau** [comment]
Unable to reproduce. It would be great to have repro steps!

**Comment by RegNex** [comment]
after integrating the plugin, my app keeps crushing on ios

<img width="1397" alt="Screen Shot 2020-03-24 at 9 03 27 PM" src="https://user-images.githubusercontent.com/19475061/77476687-ecd3ed80-6e12-11ea-890e-0a46c6b97680.png">

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.15.22-pre.24, on Mac OS X 10.15.3 19D76, locale
    en-VI)

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.6)
[✓] IntelliJ IDEA Ultimate Edition (version 2019.1)
[✓] VS Code (version 1.43.2)
[✓] Connected device (4 available)

• No issues found!
```
