### ISSUE TITLE
Unable to use 1.4.0 for IOS

### ISSUE THREAD

**Issue by sanjayjaras** [sidlatau/flutter_document_picker#21]
I am using release 1.4.0. It's working fine with android however I am getting. following error while building IOS app. 
/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_document_picker-1.4.0/ios/Classes/FlutterDocumentPickerPlugin.m:2:9: fatal error: 'flutter_document_picker/flutter_document_picker-Swift.h' file not found
    #import <flutter_document_picker/flutter_document_picker-Swift.h>
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

**Comment by sidlatau** [comment]
That is a common problem when Swift plugin is used in non Swift project. Check the link below for possible solution.

https://github.com/sidlatau/flutter_email_sender/issues/8
