### ISSUE TITLE
How to choose a directory?

### ISSUE THREAD

**Issue by Makdir** [sidlatau/flutter_document_picker#24]
I need to select only a path to a directory with files. Can flutter_document_picker do this? I tried to use the appropriate MIME types, but did not get any result.

**Comment by sidlatau** [comment]
No, this plugin does not have the ability to restrict files by the path. 
For MIME types - check v3.0.0 - ability to filter by multiple MIME types was added.

**Comment by tomekit** [comment]
I am wondering if there is any change since 2019? Apparently the Swift API: https://developer.apple.com/documentation/uikit/view_controllers/providing_access_to_directories allows doing it like this:
```Swift
let documentPicker =  UIDocumentPickerViewController(forOpeningContentTypes: [.folder])
```
