### ISSUE TITLE
After copying file to the cache directory, the file is corrupted

### ISSUE THREAD

**Issue by przemyslawsikora** [sidlatau/flutter_document_picker#3]
The issue is related to the invalid file copying process, where the target file has wrong size (always x*1024 bytes, x=1,2,3...)

To fix this:
File android/src/main/kotlin/com/sidlatau/flutterdocumentpicker/FlutterDocumentPickerDelegate.kt
Line 160
Replace with this:
```
BufferedInputStream(context.contentResolver.openInputStream(uri)).use { inputStream ->
	BufferedOutputStream(FileOutputStream(file)).use { outputStream ->
		val buf = ByteArray(1024)
		var len = inputStream.read(buf)
		while (len != -1) {
			outputStream.write(buf, 0, len)
			len = inputStream.read(buf)
		}
	}
}
```

**Comment by sidlatau** [comment]
@przemyslawsikora thanks for registering an issue! I have released package v1.0.1 with suggested fix.
