### ISSUE TITLE
Support for Web

### ISSUE THREAD

**Issue by AkshayNG** [sidlatau/flutter_document_picker#34]
Hi, I'm using `flutter_document_picker: ^3.0.1` on flutter web. Its not opening any document picker with the following code:

```
FlutterDocumentPicker.openDocument().then((path) {
      setState(() {
        voucherFilePath = path;
      });
    }).catchError((error){
      print(error);
    });
```
No error is catched.

```
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel master, v1.15.2-pre.9, on Mac OS X 10.14.6 18G95, locale en-IN)
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
[✓] Xcode - develop for iOS and macOS (Xcode 11.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 3.5)
[✓] VS Code (version 1.40.2)
[✓] Connected device (3 available)

• No issues found!

Process finished with exit code 0.
```

Not sure whether the plugin has support for web. But I can see the web caption ob pub.dev:

![Screenshot 2020-02-07 at 5 00 44 PM](https://user-images.githubusercontent.com/15035623/74026339-fa045c80-49cb-11ea-99d7-0907e39bbb7e.png)

**Comment by sidlatau** [comment]
Thanks for registering an issue! 
Unfortunately, the plugin does not support web platform. I have removed web platform badge from [pub.dev](http://pub.dev)
