### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by AndreHaueisen** [sidlatau/flutter_document_picker#4]
I'm trying to use your plugin, but after I put its dependency on pubspec.yaml I get the following error.

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':flutter_document_picker'.
> Failed to notify project evaluation listener.
   > java.lang.AbstractMethodError (no error message)

```
Any ideas?
Am I missing any configuration steps?

**Flutter Doctor**
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel master, v0.8.5-pre.5, on Microsoft Windows [Version 10.0.17134.285], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK 27.0.3)
[√] Android Studio (version 3.1)
[√] VS Code (version 1.27.2)
[√] Connected devices (1 available)

• No issues found!

**Comment by sidlatau** [comment]
It could be related to Kotlin version you are using. It looks as same problem as in issue #2 . Could you check this comment: https://github.com/sidlatau/flutter_document_picker/issues/2#issuecomment-420411084  - update Kotlin version in your project and check if it helps?

**Comment by AndreHaueisen** [comment]
Yes. Same problem. Thanks for the help.
