### ISSUE TITLE
method channel

### ISSUE THREAD

**Issue by AnkushCodes** [sidlatau/flutter_document_picker#43]
**sdk level 3.0**

error shown

android\src\main\kotlin\com\sidlatau\flutterdocumentpicker\FlutterDocumentPickerPlugin.kt: (74, 28):
Type mismatch: inferred type is Activity? but Activity was expected

android\src\main\kotlin\com\sidlatau\flutterdocumentpicker\FlutterDocumentPickerPlugin.kt: (86, 33):
 Type mismatch: inferred type is BinaryMessenger? but BinaryMessenger was expected

**Comment by sidlatau** [comment]
Problem should be fixed in v5.1.0
