### ISSUE TITLE
File Extension filter not working

### ISSUE THREAD

**Issue by ThinkDigitalRepair** [sidlatau/flutter_document_picker#5]
I entered an `allowedFileExtension` in the params, but it didn't filter the list.
<img width="1054" alt="screen shot 2018-09-21 at 9 28 12 pm" src="https://user-images.githubusercontent.com/23037821/45913345-78fff180-bde5-11e8-83ee-63dd29986f5a.png">

**Comment by ThinkDigitalRepair** [comment]
Oh.... How much control do you have over what shows up in the list?

**Comment by sidlatau** [comment]
Files  can be filtered by MIME types in Android. I just release plugin v1.1.0 version where I added optional parameter `allowedMimeType`. Previously `*/*` MIME type was used, now it becomes customisable.

As I understand you want to select files with custom extensions `*.db`, yes? The closest MIME type that works for me is `application/octet-stream`. Not all files will be filtered but for example it would not show images, videos, text files there.
In iOS you can register custom UTI type (instructions [there](https://developer.apple.com/library/archive/qa/qa1587/_index.html)).

Example:
```
FlutterDocumentPickerParams params = FlutterDocumentPickerParams(      
  allowedFileExtensions: ['db'],
  allowedUtiTypes: ['your.domain.db'],
  allowedMimeType: 'application/octet-stream',
);

final path = await FlutterDocumentPicker.openDocument(params: params);
```

Does `allowedMimeType` parameter solves your problem?

**Comment by ThinkDigitalRepair** [comment]
It sounds like it will be closer to what I'm looking for. I'll try it out
when I get on my computer again. Thank you!
-- 
Think Digital
323-638-9448
760-678-8833
Facebook.com/ThinkDigitalRepair

**Comment by sidlatau** [comment]
I found in [documentation](https://developer.android.com/reference/android/content/Intent#ACTION_OPEN_DOCUMENT):

> Callers can set a document URI through DocumentsContract.EXTRA_INITIAL_URI to indicate the initial location of documents navigator. System will do its best to launch the navigator in the specified document if it's a folder, or the folder that contains the specified document if not.

So it seems it is possible to set initial directory, at least in Android part. Need to check is it possible in iOS part.

Currently I have no plans to add this initial directory functionality to this plugin but PRs are welcome!

**Comment by ThinkDigitalRepair** [comment]
Ok, I'll see if I have a need in my app for it. But it seems like there
could be a strong use case, for example if someone needs to find a download
or if they want to start in the SD card always. If I need it, I'll try to
submit a PR
