### ISSUE TITLE
Unsupported Swift Version

### ISSUE THREAD

**Issue by luckycuizon** [sidlatau/flutter_document_picker#8]
**Problem:**
  The target "flutter_document_picker" contains source code developed with Swift 2.x. Xcode 9 does not support building or migrating to Swift 2.x targets.

**Additional Information:**
    ** BUILD FAILED **
Xcode's output:
↳
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.
The “Swift Language Version” (SWIFT_VERSION) build setting must be set to a supported value for targets which use Swift. Supported values are: 3.0, 4.0, 4.2. This setting can be set in the build settings editor.
Could not build the precompiled application for the device.

**Details ( where the problem exist):**
 -  Xcode version 10.0 with Swift 4.2 pre-installed.
 - Flutter 0.9.2 • channel dev • https://github.com/flutter/flutter.git
Framework • revision 85b4670b2a (11 days ago) • 2018-09-19 14:59:23 -0700
Engine • revision 2e8e96fad1
Tools • Dart 2.1.0-dev.4.0.flutter-4eb879133a
- flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel dev, v0.9.2, on Mac OS X 10.13.6 17G65, locale en-SG)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.2)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.1)
[✓] IntelliJ IDEA Community Edition (version 2018.1.5)
[!] Connected devices
    ! No devices available

**Comment by sidlatau** [comment]
It looks like an [issue](https://github.com/flutter/flutter/issues/16049) registered in flutter repo, when trying to add swift plugin to objective-c project. Check this comment for possible fix: 
https://github.com/flutter/flutter/issues/16049#issuecomment-382629492
